### ISSUE TITLE
Requires SDK version <2.0.0

### ISSUE THREAD

**Issue by lucaciotti** [nitishk72/youtube_api#1]
Hi,
I started using your package for one of my applications.
However, after upgrading Flutter and upgrading the Dart SDK version, I get the following error.

```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because youtube_api 0.2.1 requires SDK version <2.0.0 and no versions of youtube_api match >0.2.1 <0.3.0, youtube_api ^0.2.1 is forbidden.
So, because "myApp" depends on youtube_api ^0.2.1, version solving failed.
pub get failed (1)
```

Thanks for your help

**Comment by nitishk72** [comment]
I had built this very earlier and now I am not making the update for this.
 I am sorry for that

You can have a look at this file: https://github.com/nitishk72/youtube_api/blob/master/lib/youtube_api.dart#L32

*I was only making a request to youtube API* and I was getting the result you can see that at above link.

If you found any difficulties in doing that then let me know
