### ISSUE TITLE
Bug: Space in Url and invalid url for playlist & channel

### ISSUE THREAD

**Issue by cvaditya1** [nitishk72/youtube_api#17]
1) Space is present in the url of a video.
2) Channel and playlist have invalid url respectively

**Comment by cvaditya1** [comment]
Fix: https://github.com/nitishk72/youtube_api/pull/16

**Comment by ThinkDigitalSoftware** [comment]
Still seeing this issue using `youtube_api: ^0.7.2`
<img width="716" alt="Screen Shot 2019-11-14 at 1 27 17 PM" src="https://user-images.githubusercontent.com/23037821/68897541-91feec80-06e2-11ea-9b26-47836222ef4a.png">

**Comment by nitishk72** [comment]
I'll fix it today
