### ISSUE TITLE
nextPage() function only works 3 times

### ISSUE THREAD

**Issue by WianSnyman** [nitishk72/youtube_api#31]
Hi there. When trying to call next page more than three times it returns no results.

**Comment by WianSnyman** [comment]
Also, an exception is thrown when calling nextPage() when there are fewer videos available than maxResult.

**Comment by amrishashok** [comment]
Did you managed to find any solution?

**Comment by WianSnyman** [comment]
Yes.. I coded my own youtube API integrator

**Comment by dupuisdavid** [comment]
The problem is at the end of _api.dart file:

```
void setNextPageToken(String token) => this.nextPageToken = token;
void setPrevPageToken(String token) => this.nextPageToken = token;
```

When the nextPage method is called, the next page token is incorrectly overridden with the previous page token.

**Comment by nitishk72** [comment]
fixed and @dupuisdavid thanks for pointing out
