### ISSUE TITLE
Issue in installing

### ISSUE THREAD

**Issue by jabirmayar** [nitishk72/youtube_api#38]
Please Fix: ```
The plugin `youtube_api` doesn't have a main class defined in C:\flutter\.pub-cache\git\youtube_api-75fefcbfa15ef78119315854d5e69c16f83ea2c0\android\src\main\java\io\github\nitishk72\youtubeapi\YoutubeApiPlugin.java or C:\flutter\.pub-cache\git\youtube_api-75fefcbfa15ef78119315854d5e69c16f83ea2c0\android\src\main\kotlin\io\github\nitishk72\youtubeapi\YoutubeApiPlugin.kt. This is likely to due to an incorrect `androidPackage: io.github.nitishk72.youtubeapi` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
exit code 1
```

**Comment by nitishk72** [comment]
use 0.9.0 for now
I'll fix it ASAP

**Comment by nitishk72** [comment]
fixed it and also transferred to the https://github.com/nstack-in/youtube_api

**Comment by jabirmayar** [comment]
@nitishk72  Thank you. It is fixed but can you please look into the search by the channel id as it is not working. When I search by channel it gives 
" Unhandled Exception: Null check operator used on a null value".
Edit: 
Only works if add order to the `ytApi.channel("channelid",order: "date");`

**Comment by nitishk72** [comment]
fixed just now
check v0.9.6
