### ISSUE TITLE
There are 3 merge conflicts in the youtube_api.dart which need to be resolved in the version youtube_api: ^0.5.1

### ISSUE THREAD

**Issue by AnuragBanger** [nitishk72/youtube_api#7]
`Your application could not be compiled, because its dependencies could not be established.
When trying to parse this Dart file to find its dependencies:
  /Users/macmini/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_api-0.5.1/lib/youtube_api.dart
...the analyzer failed with the following error:
Error in /Users/macmini/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_api-0.5.1/lib/youtube_api.dart: The '===' operator is not supported.`

**Comment by nitishk72** [comment]
Issue resolved
