### ISSUE TITLE
The '===' operator is not supported.

### ISSUE THREAD

**Issue by the-maunda** [nitishk72/youtube_api#8]
.pub-cache/hosted/pub.dartlang.org/youtube_api-0.5.1/lib/youtube_api.dart:

**Comment by g-casey** [comment]
I'm also getting this

**Comment by strbbrn** [comment]
same problem facing but after some modification on youtube_api.dart 
I got this much of result
`I/flutter ( 5011): videoId
I/flutter ( 5011): mx7F-BlNxEI
I/flutter ( 5011): channelId
I/flutter ( 5011): UCwXdFgeE9KYzlDdR7TG9cMw
I/flutter ( 5011): videoId
I/flutter ( 5011): 8pJ7lJNiGkA
I/flutter ( 5011): videoId
I/flutter ( 5011): ymyYUCrJnxU
I/flutter ( 5011): videoId
I/flutter ( 5011): GLSG_Wh_YWc
I/flutter ( 5011): playlistId
I/flutter ( 5011): PLOU2XLYxmsIJ7dsVN4iRuA7BT8XHzGtCr
I/flutter ( 5011): videoId
I/flutter ( 5011): 9iUMZA46_8k
I/flutter ( 5011): videoId
I/flutter ( 5011): kpcjBD1XDwU
I/flutter ( 5011): videoId
I/flutter ( 5011): W1pNjxmNHNQ
I/flutter ( 5011): videoId
I/flutter ( 5011): lNqEfnnmoHk`

**Comment by nitishk72** [comment]
There is no more error.
Try again
